### ISSUE TITLE
New problem with aquire

### ISSUE THREAD

**Issue by dSabulsky** [jstammers/Camera-Software#4]
When you run live camera, it will only take 32 images and then freeze.

**Comment by dSabulsky** [comment]
Description:
  A problem caused this program to stop interacting with Windows.

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	pythonw.exe
  Application Version:	0.0.0.0
  Application Timestamp:	55678c56
  Hang Signature:	5557
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Hang Signature 1:	555775b85b50ac3b1746a6d760474d49
  Additional Hang Signature 2:	b306
  Additional Hang Signature 3:	b3069bb070d51e97aae728bccc18b329
  Additional Hang Signature 4:	5557
  Additional Hang Signature 5:	555775b85b50ac3b1746a6d760474d49
  Additional Hang Signature 6:	b306
  Additional Hang Signature 7:	b3069bb070d51e97aae728bccc18b329

**Comment by jstammers** [comment]
This seems to be fixed when running python with the console open (python.exe as opposed to pythonw.exe)
