### ISSUE TITLE
cam_stripdown crashing

### ISSUE THREAD

**Issue by dSabulsky** [jstammers/Camera-Software#6]
The cam_stripdown data logging program crashes and will not open for me. 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	pythonw.exe
  Application Version:	0.0.0.0
  Application Timestamp:	55678c56
  Fault Module Name:	wxbase30u_vc90_x64.dll
  Fault Module Version:	3.0.2.0
  Fault Module Timestamp:	5477a662
  Exception Code:	c0000005
  Exception Offset:	0000000000126190
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	eebf
  Additional Information 2:	eebfab59b65cc1f0cf83ea1ebb33fbce
  Additional Information 3:	2805
  Additional Information 4:	280537a60543402b687b295203d5bea5

**Comment by jstammers** [comment]
I don't think this is a problem with cam. Try opening with python via the command line
